# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x05unary\"b\n\rCoordinateSet\x12&\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x11.unary.Coordinate\x12)\n\x0equery_location\x18\x02 \x01(\x0b\x32\x11.unary.Coordinate\"1\n\nCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"X\n\x17NearestLocationResponse\x12+\n\x10nearest_location\x18\x01 \x01(\x0b\x32\x11.unary.Coordinate\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x32T\n\x08Trashify\x12H\n\x0eGetNearestCoor\x12\x14.unary.CoordinateSet\x1a\x1e.unary.NearestLocationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATESET']._serialized_start=21
  _globals['_COORDINATESET']._serialized_end=119
  _globals['_COORDINATE']._serialized_start=121
  _globals['_COORDINATE']._serialized_end=170
  _globals['_NEARESTLOCATIONRESPONSE']._serialized_start=172
  _globals['_NEARESTLOCATIONRESPONSE']._serialized_end=260
  _globals['_TRASHIFY']._serialized_start=262
  _globals['_TRASHIFY']._serialized_end=346
# @@protoc_insertion_point(module_scope)
